### ISSUE TITLE
Failed to delete resource sharing request

### ISSUE THREAD

**Issue by jasonhallen** [ExLibrisGroup/Cloud-App-Change-RS-Requests#10]
Hello,

We have a staff person who gets the following error message when running this app:

![image](https://user-images.githubusercontent.com/60990234/178008339-025435ca-fc86-4075-9f59-5521be18091a.png)

The new request is created, but the old request isn't deleted.  She has Fulfillment Services Operator and Fulfillment Services Manager user roles at both the resource sharing library level and the institutional level.  The "Delete old requests after creating the new one" box is checked.  She uninstalled the app and reinstalled it today, but the error continues.

Can you advise on what might be causing this error?  Since the error message says she's not authorized to perform the action, does that mean she needs a different user role or different scopes on her current roles?

Thanks!
Jason

**Comment by ori229** [comment]
Hi Jason, 
Thanks for bringing this to my attention.
The problem seems to on Alma's side. The DELETE resource-sharing-requests API was programmed to be allowed for a wrong privilege. We'll align it with the other resource-sharing-requests APIs. 
My apologies - the earliest I can fix it is for the Sep Release. I'll leave this issue open until then.

**Comment by jasonhallen** [comment]
Thanks very much for the update!

Jason

**Comment by ori229** [comment]
Should be OK starting Sunday
